services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: donetick-core
    restart: unless-stopped
    volumes:
    - ./data:/usr/src/app/data
    ports:
    - "8085:8000"
    environment:
    - DT_ENV=prod
    hostname: donetick-core
    command: ["/donetick-core"]
