name: "local"
database:
  migration: true
  path: task-wizard.db
jwt:
  secret: "secret"
  session_time: 168h
  max_refresh: 168h
server:
  port: 2021
  read_timeout: 2s
  write_timeout: 1s
  rate_period: 60s
  rate_limit: 300
  serve_frontend: false
  debug: true
scheduler_jobs:
  due_frequency: 5s
  overdue_frequency: 10s
email:
  host: 
  port: 
  key: 
  email:  
  appHost:  
