name: "prod"
database:
  migration: true
  path: /config/task-wizard.db
jwt:
  secret: "secret"
  session_time: 168h
  max_refresh: 168h
server:
  port: 2021
  read_timeout: 2s
  write_timeout: 1s
  rate_period: 60s
  rate_limit: 300
  serve_frontend: true
scheduler_jobs:
  frequency: 5m
email:
  host: 
  port: 
  key: 
  email:  
  appHost:  
