name: Go Release

permissions:
  contents: write
  
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push Docker Image
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Checkout Frontend
        uses: actions/checkout@v4
        with:
          repository: '${{ vars.FRONTEND_REPO }}'
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ vars.FRONTEND_REF }}
          path: 'frontend-code'
      # build frontend 
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Dependencies
        run: |
          cd frontend-code
          yarn install
      - name: Build Frontend
        run: |
          cd frontend-code
          yarn build

      - name: Copy Frontend
        run: |
          rm -rf ./frontend/dist
          cp -r frontend-code/dist ./frontend/dist

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
          check-latest: true
          cache: true 

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@90a3faa9d0182683851fbfa97ca1a2cb983bfca3 #v6.2.1
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: latest
          args: release --clean --skip=validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # I added QEMU Emulation support for non-native architectures and also Buildx to enables multi-architecture. not sure if there is better/faster way to do this
      - name: Set up QEMU 
        uses: docker/setup-qemu-action@4574d27a4764455b42196d70a065bc6853246a25 #v3.4.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca #v3.9.0

      - name: Log in to Docker Hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 #v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ca877d9245402d1537745e0e356eab47c3520991 #v6.13.0
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/task-wizard:latest, ${{ secrets.DOCKER_USERNAME }}/task-wizard:${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
